# -*- coding: utf-8 -*-
"""Traductions anglaises du catalogue de processus, INDEXEES PAR SLUG.

Le slug (nom de fichier .bxflow sans son prefixe numerique, ex.
`note-de-frais`, `entree-en-relation-kyc`) est la cle stable : contrairement
au rang du portefeuille, il ne bouge pas si un `.bxflow` est insere ou
reordonne. UNE FOIS PUBLIE, un slug ne change plus — si un fichier `.bxflow`
est un jour renomme, ajouter une redirection 301 plutot que de changer le
slug qu'il porte ici.

Trois tables :
- ROLES : les 5 roles du portefeuille, UNE traduction chacun (partagee par
  tous les processus qui les emploient).
- TRANSITIONS_COMMUNES : les transitions qui reviennent dans plusieurs
  processus (« Valider », « Rejeter »...) — memes raisons, meme traduction.
- PROCESSUS : le reste, propre a chaque processus. `steps` couvre TOUTES les
  etapes (y compris terminales, affichees sur la page processus mais pas sur
  la carte du catalogue). `transitions` ne liste QUE les transitions absentes
  de TRANSITIONS_COMMUNES — le reste s'y resout automatiquement.
"""

ROLES: dict[str, str] = {
    'wf_compliance': 'Compliance / AML-CFT',
    'wf_finance': 'Finance / Accounting',
    'wf_juridique': 'Legal',
    'wf_risk': 'Risk',
    'wf_rssi': 'Information Security',
}

TRANSITIONS_COMMUNES: dict[str, str] = {
    'Valider': 'Approve',
    'Rejeter': 'Reject',
    'Renvoyer pour correction': 'Return for correction',
    'Annuler': 'Cancel',
    'Soumettre': 'Submit',
    'Clôturer': 'Close',
    'Soumettre pour avis': 'Submit for review',
    'Soumettre à validation': 'Submit for approval',
    'Transmettre à la conformité': 'Refer to Compliance',
    'Soumettre la déclaration': 'Submit the report',
    'Ajourner': 'Defer',
    'Soumettre au RSSI': 'Refer to Information Security',
    'Lancer la vérification': 'Start verification',
    'Transmettre au juridique': 'Refer to Legal',
    'Lancer l\'évaluation': 'Start the assessment',
    'Soumettre la demande': 'Submit the request',
}

PROCESSUS: dict[str, dict] = {
    'demande-de-conges': {
        'slug_en': 'leave-request',
        'name': 'Leave request',
        'description': 'Leave and absence requests',
        'steps': {
            'nouvelle_demande': 'New request',
            'en_attente_approbation': 'Awaiting approval',
            'approuve': 'Approved',
            'refuse': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'note-de-frais': {
        'slug_en': 'expense-report',
        'name': 'Expense report',
        'description': 'Submission and reimbursement of business expenses',
        'steps': {
            'nouvelle_note': 'New report',
            'verification_comptable': 'Accounting check',
            'approbation_direction': 'Senior management approval',
            'en_paiement': 'Payment in progress',
            'rembourse': 'Reimbursed',
            'refuse_frais': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-valider-compta': 'Approve (accounting)',
            't-confirmer-paiement': 'Confirm payment',
        },
    },
    'ticket-support': {
        'slug_en': 'support-ticket',
        'name': 'Support ticket',
        'description': 'Requests, incidents and bugs',
        'steps': {
            'nouveau_ticket': 'New ticket',
            'qualification': 'Triage',
            'en_cours': 'In progress',
            'resolu': 'Resolved',
            'clos_ticket': 'Closed',
            'abandonne': 'Canceled',
            'fin_rejete': 'Rejected',
        },
        'transitions': {
            't-qualifier': 'Take in charge',
            't-traiter': 'Start handling',
            't-abandonner': 'Abandon',
            't-resoudre': 'Mark resolved',
            't-reopen': 'Reopen',
        },
    },
    'demande-achat': {
        'slug_en': 'purchase-request',
        'name': 'Purchase request',
        'description': 'Purchase approval circuit',
        'steps': {
            'nouvelle_demande_achat': 'New request',
            'validation_n1': 'Line manager approval',
            'validation_n2': 'Second-level approval (high amount)',
            'en_commande': 'On order',
            'livre_achat': 'Delivered',
            'rejete_achat': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-approuver-n1-escalade': 'Escalate to second level (high amount)',
            't-confirmer-livraison': 'Confirm delivery',
        },
    },
    'onboarding-collaborateur': {
        'slug_en': 'employee-onboarding',
        'name': 'Employee onboarding',
        'description': 'Bringing a new employee on board',
        'steps': {
            'nouvelle_arrivee': 'New arrival',
            'preparation_it': 'IT preparation',
            'accueil_rh': 'HR welcome',
            'integration_active': 'Onboarding in progress',
            'onboarding_complete': 'Onboarding complete',
            'onboarding_annule': 'Canceled',
            'fin_rejete': 'Rejected',
        },
        'transitions': {
            't-initier-onboarding': 'Start onboarding',
            't-valider-preparation': 'Approve preparation',
        },
    },
    'reclamation-client': {
        'slug_en': 'customer-complaint',
        'name': 'Customer complaint',
        'description': 'Complaints and disputes',
        'steps': {
            'nouvelle_reclamation': 'New complaint',
            'analyse_reclamation': 'Analysis',
            'traitement_reclamation': 'Handling',
            'escalade_reclamation': 'Escalated to management',
            'clos_recl': 'Closed',
            'rejete_recl': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-enregistrer-recl': 'Register',
            't-analyser-recl': 'Analyze and handle',
            't-escalader-recl': 'Escalate',
        },
    },
    'habilitations-acces': {
        'slug_en': 'access-rights',
        'name': 'Access rights',
        'description': 'Access requests to applications, databases and internal tools',
        'steps': {
            'demande_hab': 'New request',
            'validation_manager_hab': 'Manager approval',
            'validation_applicative_hab': 'Application owner approval',
            'application_acces_hab': 'Access provisioning',
            'acces_accorde': 'Access granted',
            'acces_refuse': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-confirmer-acces-hab': 'Confirm access granted',
        },
    },
    'change-management': {
        'slug_en': 'application-change-management',
        'name': 'Application change management',
        'description': 'Changes and releases on business applications',
        'steps': {
            'soumission_change': 'Submission',
            'analyse_it': 'IT analysis',
            'validation_applicative_change': 'Application owner approval',
            'comite_changement': 'Change committee',
            'deploiement_change': 'Deployment',
            'change_effectue': 'Change completed',
            'annule_change': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-transmettre-validation': 'Refer for approval',
            't-escalader-comite': 'Escalate to committee',
            't-confirmer-deploiement': 'Confirm deployment',
        },
    },
    'contrats-fournisseurs': {
        'slug_en': 'supplier-contracts',
        'name': 'Supplier contracts',
        'description': 'Reviewing and securing supplier contracts before signature',
        'steps': {
            'creation_contrat': 'Contract filing',
            'analyse_juridique_contrat': 'Legal review',
            'validation_financiere_contrat': 'Financial approval',
            'signature_direction_contrat': 'Executive signature',
            'archive_contrat': 'Archived',
            'refuse_contrat': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-soumettre-contrat': 'Submit to Legal',
        },
    },
    'formations-collaborateurs': {
        'slug_en': 'employee-training',
        'name': 'Employee training',
        'description': 'Training requests',
        'steps': {
            'demande_formation': 'Training request',
            'validation_manager_formation': 'Manager approval',
            'controle_budget_rh': 'HR budget check',
            'formation_confirmee': 'Training confirmed',
            'formation_refusee': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'deplacements-professionnels': {
        'slug_en': 'business-travel',
        'name': 'Business travel',
        'description': 'Assignments and business trips',
        'steps': {
            'demande_deplacement': 'Travel request',
            'validation_manager_deplacement': 'Manager approval',
            'validation_finance_deplacement': 'Financial approval',
            'deplacement_confirme': 'Travel confirmed',
            'deplacement_refuse': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'recrutement': {
        'slug_en': 'recruitment-campaign',
        'name': 'Recruitment campaign',
        'description': 'From opening a position to the candidate joining',
        'steps': {
            'besoin_recrutement': 'Hiring need',
            'validation_rh_recrutement': 'HR approval',
            'validation_budget_recrutement': 'Budget approval',
            'traitement_candidatures': 'Candidate processing',
            'validation_candidat_final': 'Final candidate approval',
            'poste_pourvu': 'Position filled',
            'annule_recrutement': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-soumettre-besoin': 'Submit the need',
            't-selectionner-candidat': 'Select a candidate',
        },
    },
    'audits-internes': {
        'slug_en': 'internal-audits',
        'name': 'Internal audits',
        'description': 'Planning internal audits and tracking corrective actions',
        'steps': {
            'planification_audit': 'Planning',
            'realisation_audit': 'Fieldwork',
            'validation_rapport_audit': 'Report approval',
            'suivi_actions_audit': 'Corrective action follow-up',
            'cloture_audit': 'Closed',
            'annule_audit': 'Canceled',
            'fin_rejete': 'Rejected',
        },
        'transitions': {
            't-lancer-audit': 'Start the audit',
            't-soumettre-rapport': 'Submit the report',
            't-cloturer-suivi': 'Close the audit',
        },
    },
    'demandes-juridiques': {
        'slug_en': 'internal-legal-requests',
        'name': 'Internal legal requests',
        'description': 'Requests addressed to the legal department',
        'steps': {
            'demande_juridique': 'Request',
            'qualification_juridique': 'Triage',
            'analyse_juridique_step': 'Legal review',
            'avis_juridique': 'Legal opinion issued',
            'cloture_juridique': 'Closed',
            'annule_juridique': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-qualifier-demande': 'Triage and analyze',
            't-annuler-qualification': 'Reject (out of scope)',
        },
    },
    'evaluations-annuelles': {
        'slug_en': 'annual-reviews',
        'name': 'Annual reviews',
        'description': 'Annual appraisal campaigns',
        'steps': {
            'lancement_evaluation': 'Campaign launch',
            'entretien_manager_eval': 'Manager interview',
            'commentaire_collaborateur_step': 'Employee comment',
            'validation_manager_eval': 'Manager approval',
            'cloture_rh_eval': 'Closed by HR',
            'annule_eval': 'Canceled',
            'fin_rejete': 'Rejected',
        },
        'transitions': {
            't-lancer-eval': 'Start the review',
            't-conduire-entretien': 'Open for employee comment',
            't-ajouter-commentaire': 'Submit my comment',
        },
    },
    'offboarding': {
        'slug_en': 'employee-offboarding',
        'name': 'Employee offboarding',
        'description': 'Securing an employee\'s departure',
        'steps': {
            'lancement_offboarding': 'Launch',
            'confirmation_manager_offboarding': 'Manager confirmation',
            'desactivation_it': 'IT deactivation',
            'restitution_materiel': 'Equipment return',
            'cloture_rh_offboarding': 'Closed by HR',
            'annule_offboarding': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-lancer-offboarding': 'Start the process',
            't-desactiver-acces': 'Access deactivated',
            't-cloturer-offboarding': 'Close departure',
        },
    },
    'declaration-operation-suspecte': {
        'slug_en': 'suspicious-activity-report',
        'name': 'Suspicious activity report',
        'description': 'AML/CFT reporting of an unusual transaction by an employee, compliance analysis, and a filing decision to the national Financial Intelligence Unit (FIU) — CENTIF in the UEMOA zone, ANIF in the CEMAC zone, UTRF in Morocco.',
        'steps': {
            'dos_signalement': 'Report drafting',
            'dos_analyse': 'Compliance analysis',
            'dos_decision': 'Filing decision',
            'dos_transmission': 'Referral to the Financial Intelligence Unit (FIU)',
            'dos_declare': 'Filed',
            'dos_classe': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-dos-confirmer-envoi': 'Confirm submission',
        },
    },
    'entree-en-relation-kyc': {
        'slug_en': 'customer-onboarding-kyc',
        'name': 'Client onboarding (KYC)',
        'description': 'Opening a business relationship',
        'steps': {
            'eer_collecte': 'File collection',
            'eer_verification': 'Document verification',
            'eer_criblage': 'Screening and scoring',
            'eer_validation': 'Compliance approval',
            'eer_ouverte': 'Relationship opened',
            'eer_refusee': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-eer-soumettre': 'Submit the file',
        },
    },
    'revue-periodique-kyc': {
        'slug_en': 'periodic-kyc-review',
        'name': 'Periodic KYC review',
        'description': 'Updating the client knowledge file at the interval set by the segment',
        'steps': {
            'rkyc_planification': 'Review planning',
            'rkyc_collecte': 'Collection from the client',
            'rkyc_analyse': 'Analysis and re-rating',
            'rkyc_validation': 'Compliance approval',
            'rkyc_clos': 'Review closed',
            'rkyc_escalade': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-rkyc-lancer': 'Start the review',
        },
    },
    'validation-client-risque-eleve': {
        'slug_en': 'high-risk-client-approval-pep',
        'name': 'High-risk client approval (PEP)',
        'description': 'Escalation of a politically exposed or high-risk client',
        'steps': {
            'ppe_signalement': 'Case referral',
            'ppe_analyse': 'Compliance analysis',
            'ppe_direction': 'Executive approval',
            'ppe_accepte': 'Relationship authorized',
            'ppe_refuse': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-ppe-escalader': 'Escalate to Compliance',
        },
    },
    'declaration-conflit-interet': {
        'slug_en': 'conflict-of-interest-disclosure',
        'name': 'Conflict of interest disclosure',
        'description': 'Disclosure of a potential or actual conflict of interest',
        'steps': {
            'cdi_declaration': 'Disclosure',
            'cdi_avis_hierarchique': 'Manager review',
            'cdi_analyse': 'Ethics officer review',
            'cdi_enregistre': 'Recorded in the register',
            'cdi_refuse': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'declaration-cadeau-invitation': {
        'slug_en': 'gift-and-hospitality-disclosure',
        'name': 'Gift and hospitality disclosure',
        'description': 'Disclosure of a gift or invitation received or offered',
        'steps': {
            'cad_declaration': 'Disclosure',
            'cad_controle': 'Threshold check',
            'cad_decision': 'Ethics officer decision',
            'cad_enregistre': 'Recorded in the register',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'comite-nouveau-produit': {
        'slug_en': 'new-product-committee',
        'name': 'New product committee',
        'description': 'Review of a new product, service or distribution channel',
        'steps': {
            'npap_cadrage': 'Scoping',
            'npap_avis_risques_step': 'Risk review',
            'npap_avis_conformite_step': 'Compliance and legal review',
            'npap_comite': 'Committee review',
            'npap_approuve': 'Product approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'revue-reglementaire': {
        'slug_en': 'regulatory-review',
        'name': 'Regulatory review',
        'description': 'Taking a new regulatory text into account',
        'steps': {
            'reg_veille': 'Watch',
            'reg_analyse': 'Impact analysis',
            'reg_plan': 'Compliance plan',
            'reg_validation': 'Compliance approval',
            'reg_conforme': 'Compliant',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-reg-analyser': 'Open the analysis',
        },
    },
    'declaration-incident-operationnel': {
        'slug_en': 'operational-incident-report',
        'name': 'Operational incident report',
        'description': 'Collecting an operational incident under the Basel taxonomy',
        'steps': {
            'inc_declaration': 'Incident reporting',
            'inc_qualification': 'Assessment and costing',
            'inc_analyse': 'Analysis and action plan',
            'inc_cloture': 'Closure by Risk',
            'inc_enregistre': 'Recorded in the loss database',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-inc-transmettre': 'Refer to Risk',
        },
    },
    'auto-evaluation-risques-rcsa': {
        'slug_en': 'risk-self-assessment-rcsa',
        'name': 'Risk self-assessment (RCSA)',
        'description': 'Self-assessment of risks and controls by entity',
        'steps': {
            'rcsa_lancement': 'Campaign launch',
            'rcsa_autoevaluation': 'Self-assessment by the entity',
            'rcsa_challenge': 'Risk challenge',
            'rcsa_traitement': 'Treatment decision',
            'rcsa_valide': 'Assessment approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-rcsa-lancer': 'Start the self-assessment',
        },
    },
    'campagne-controle-permanent': {
        'slug_en': 'permanent-control-campaign',
        'name': 'Permanent control campaign',
        'description': 'Running a second-line control from the plan',
        'steps': {
            'ctrl_planification': 'Planning',
            'ctrl_execution': 'Control execution',
            'ctrl_supervision': 'Risk supervision',
            'ctrl_remediation': 'Remediation',
            'ctrl_clos': 'Control closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-ctrl-lancer': 'Start the control',
            't-ctrl-cloturer-sans-anomalie': 'Close with no findings',
        },
    },
    'suivi-recommandations-audit': {
        'slug_en': 'audit-recommendation-follow-up',
        'name': 'Audit recommendation follow-up',
        'description': 'Following a recommendation from internal audit or inspection',
        'steps': {
            'reco_enregistrement': 'Recording',
            'reco_plan': 'Action plan',
            'reco_mise_en_oeuvre': 'Implementation',
            'reco_verification': 'Verification by the issuer',
            'reco_levee': 'Recommendation closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-reco-engager': 'Start the action plan',
            't-reco-reporter': 'Extend the deadline',
        },
    },
    'declaration-incident-securite': {
        'slug_en': 'security-incident-report',
        'name': 'Security incident report',
        'description': 'Handling an information security incident',
        'steps': {
            'sec_declaration': 'Incident reporting',
            'sec_qualification': 'Assessment',
            'sec_traitement': 'Handling and notification',
            'sec_retex': 'Lessons learned',
            'sec_clos': 'Incident closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-sec-qualifier': 'Refer to Information Security',
        },
    },
    'validation-exception-securite': {
        'slug_en': 'security-exception-approval',
        'name': 'Security exception approval',
        'description': 'Request to deviate from a security policy rule',
        'steps': {
            'exc_demande': 'Request',
            'exc_analyse': 'CISO analysis',
            'exc_decision_step': 'Risk acceptance',
            'exc_accordee': 'Exception granted',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'revue-periodique-habilitations': {
        'slug_en': 'access-rights-recertification',
        'name': 'Access rights recertification',
        'description': 'Recertification campaign of application access rights',
        'steps': {
            'revh_lancement': 'Campaign launch',
            'revh_revue_manager': 'Manager review',
            'revh_execution': 'Access removal',
            'revh_attestation_step': 'Closure attestation',
            'revh_certifie': 'Access rights recertified',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-revh-lancer': 'Start the recertification',
        },
    },
    'validation-engagement-depense': {
        'slug_en': 'spend-commitment-approval',
        'name': 'Spend commitment approval',
        'description': 'Prior authorization of a budget commitment',
        'steps': {
            'eng_demande': 'Commitment request',
            'eng_controle': 'Budget check',
            'eng_validation': 'Approval by delegation',
            'eng_accorde': 'Commitment approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-eng-soumettre': 'Submit to Finance',
        },
    },
    'validation-facture-fournisseur': {
        'slug_en': 'supplier-invoice-approval',
        'name': 'Supplier invoice approval',
        'description': 'Checking an incoming invoice',
        'steps': {
            'fac_reception': 'Invoice intake',
            'fac_service_fait_step': 'Service confirmation',
            'fac_controle_comptable': 'Accounting check',
            'fac_litige': 'Supplier dispute',
            'fac_bon_a_payer': 'Approved for payment',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-fac-transmettre': 'Refer to the business owner',
            't-fac-mettre-en-litige': 'Open a dispute',
        },
    },
    'creation-fournisseur-comptable-rib': {
        'slug_en': 'supplier-bank-details-change',
        'name': 'Supplier bank details change',
        'description': 'Creating a third party or changing its bank details, with mandatory call-back',
        'steps': {
            'rib_demande': 'Request',
            'rib_verification': 'Call-back and verification',
            'rib_validation': 'Dual approval',
            'rib_enregistre': 'Third party recorded',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'validation-ordre-virement': {
        'slug_en': 'payment-order-approval',
        'name': 'Payment order approval',
        'description': 'Four-eyes approval circuit for a payment order',
        'steps': {
            'vir_saisie': 'Order entry',
            'vir_controle': 'Treasury check',
            'vir_signature': 'Signature',
            'vir_execute': 'Payment executed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-vir-soumettre': 'Submit for review',
        },
    },
    'demande-paiement-exceptionnel': {
        'slug_en': 'exceptional-payment-request',
        'name': 'Exceptional payment request',
        'description': 'Payment outside the normal circuit — urgency, no purchase order, off schedule',
        'steps': {
            'pex_demande': 'Request',
            'pex_instruction': 'Finance review',
            'pex_arbitrage': 'Executive arbitration',
            'pex_accorde': 'Payment approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-pex-instruire': 'Submit to Finance management',
        },
    },
    'demande-depassement-limite': {
        'slug_en': 'risk-limit-breach-request',
        'name': 'Risk limit breach request',
        'description': 'Authorization to exceed a risk limit — counterparty, sector, country',
        'steps': {
            'lim_demande': 'Request',
            'lim_analyse': 'Risk analysis',
            'lim_comite': 'Committee decision',
            'lim_accorde': 'Breach approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-lim-soumettre': 'Submit to Risk',
        },
    },
    'validation-credit-exceptionnel': {
        'slug_en': 'exceptional-credit-approval',
        'name': 'Exceptional credit approval',
        'description': 'Credit granted outside policy — rate, term, loan-to-value, collateral',
        'steps': {
            'cre_montage': 'File preparation',
            'cre_analyse': 'Credit risk analysis',
            'cre_comite': 'Credit committee',
            'cre_accorde': 'Credit approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-cre-soumettre': 'Submit for credit risk review',
        },
    },
    'validation-remise-pouvoir': {
        'slug_en': 'delegation-of-authority',
        'name': 'Delegation of authority',
        'description': 'Granting, changing or withdrawing a delegation of authority or signature',
        'steps': {
            'pouv_demande': 'Request',
            'pouv_conformite': 'Incompatibility check',
            'pouv_validation': 'Executive approval',
            'pouv_registre': 'Recorded in the register',
            'pouv_en_vigueur': 'Delegation in effect',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-pouv-soumettre': 'Submit to Compliance',
        },
    },
    'gestion-sinistres-complexes': {
        'slug_en': 'complex-claims-handling',
        'name': 'Complex claims handling',
        'description': 'Handling a high-stakes claim — large amount, several victims, suspected fraud',
        'steps': {
            'sin_declaration': 'Claim reporting',
            'sin_expertise': 'Assessment',
            'sin_garantie_step': 'Cover analysis',
            'sin_reglement': 'Settlement',
            'sin_regle': 'Claim settled',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-sin-expertiser': 'Start the expert assessment',
            't-sin-contre-expertise': 'Request a second opinion',
        },
    },
    'validation-indemnisation-exceptionnelle': {
        'slug_en': 'exceptional-settlement-approval',
        'name': 'Exceptional settlement approval',
        'description': 'Settlement outside the contract or scale — goodwill, cap exceeded',
        'steps': {
            'ind_demande': 'Request',
            'ind_avis': 'Technical review',
            'ind_decision_step': 'Executive decision',
            'ind_accorde': 'Settlement approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'referencement-courtier': {
        'slug_en': 'broker-accreditation',
        'name': 'Broker accreditation',
        'description': 'Accrediting an insurance intermediary',
        'steps': {
            'cou_demande': 'Application',
            'cou_verification': 'License verification',
            'cou_conformite': 'Compliance check',
            'cou_validation': 'Accreditation approval',
            'cou_reference': 'Intermediary accredited',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'gestion-litiges-contentieux': {
        'slug_en': 'litigation-management',
        'name': 'Litigation management',
        'description': 'Opening and following a litigation file',
        'steps': {
            'lit_ouverture': 'Case opening',
            'lit_qualification': 'Legal assessment',
            'lit_procedure': 'Proceedings monitoring',
            'lit_cloture_step': 'Case closure',
            'lit_clos': 'Litigation closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'fin-de-contrat': {
        'slug_en': 'contract-renewal-or-termination',
        'name': 'Contract renewal or termination',
        'description': 'Handling a contract deadline before notice expires',
        'steps': {
            'fct_alerte': 'Deadline alert',
            'fct_bilan': 'Relationship review',
            'fct_arbitrage_step': 'Arbitration',
            'fct_notification': 'Notice to the counterparty',
            'fct_traite': 'Deadline handled',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-fct-lancer': 'Start the review',
        },
    },
    'referencement-fournisseur': {
        'slug_en': 'supplier-accreditation',
        'name': 'Supplier accreditation',
        'description': 'Approving a new supplier',
        'steps': {
            'four_demande': 'Accreditation request',
            'four_diligence': 'Due diligence',
            'four_risque': 'Third-party risk assessment',
            'four_validation': 'Accreditation approval',
            'four_reference': 'Supplier accredited',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-four-instruire': 'Start due diligence',
        },
    },
    'evaluation-periodique-fournisseur': {
        'slug_en': 'periodic-supplier-review',
        'name': 'Periodic supplier review',
        'description': 'Performance and risk review of an accredited supplier',
        'steps': {
            'evf_lancement': 'Review launch',
            'evf_notation': 'Rating by the requester',
            'evf_revue': 'Risk review',
            'evf_decision_step': 'Panel decision',
            'evf_clos': 'Review closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'consultation-appel-offres': {
        'slug_en': 'tender-and-sourcing',
        'name': 'Tender and sourcing',
        'description': 'Putting a purchasing need out to tender',
        'steps': {
            'ao_preparation': 'Preparation',
            'ao_consultation': 'Market consultation',
            'ao_analyse': 'Bid analysis',
            'ao_attribution': 'Award',
            'ao_attribue': 'Contract awarded',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-ao-lancer': 'Start the consultation',
        },
    },
    'validation-politique-procedure': {
        'slug_en': 'internal-policy-approval',
        'name': 'Internal policy approval',
        'description': 'Life cycle of the internal documentation',
        'steps': {
            'pol_redaction': 'Drafting',
            'pol_relecture': 'Compliance and legal review',
            'pol_approbation': 'Senior management approval',
            'pol_diffusion': 'Publication',
            'pol_publie': 'Document published',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-pol-soumettre': 'Submit for review',
        },
    },
    'demande-nouveau-projet': {
        'slug_en': 'new-project-request',
        'name': 'New project request',
        'description': 'Reviewing an IT project request',
        'steps': {
            'proj_expression': 'Need definition',
            'proj_cadrage': 'Scoping and costing',
            'proj_priorisation': 'Prioritization',
            'proj_comite': 'Committee decision',
            'proj_lance': 'Project launched',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-proj-cadrer': 'Refer for scoping',
            't-proj-reporter': 'Defer',
        },
    },
    'validation-architecture': {
        'slug_en': 'architecture-approval',
        'name': 'Architecture approval',
        'description': 'Taking an architecture file to committee',
        'steps': {
            'arch_soumission': 'File submission',
            'arch_technique': 'Technical review',
            'arch_securite': 'Security review',
            'arch_comite': 'Architecture committee',
            'arch_valide': 'Architecture approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-arch-soumettre': 'Submit for review',
        },
    },
    'incident-majeur': {
        'slug_en': 'major-incident',
        'name': 'Major incident',
        'description': 'Crisis management of a critical incident',
        'steps': {
            'maj_declaration': 'Incident reporting',
            'maj_qualification': 'Assessment and crisis team',
            'maj_retablissement': 'Service restoration',
            'maj_postmortem_step': 'Lessons learned',
            'maj_clos': 'Incident closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-maj-qualifier': 'Assess the incident',
        },
    },
    'gestion-des-problemes': {
        'slug_en': 'problem-management',
        'name': 'Problem management',
        'description': 'Finding the root cause of recurring incidents',
        'steps': {
            'prb_ouverture': 'Case opening',
            'prb_analyse': 'Root cause analysis',
            'prb_solution': 'Permanent fix',
            'prb_verification_step': 'Effectiveness check',
            'prb_resolu': 'Problem resolved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-prb-analyser': 'Start the analysis',
        },
    },
    'gestion-comptes-privileges': {
        'slug_en': 'privileged-account-management',
        'name': 'Privileged account management',
        'description': 'Granting privileged or emergency access',
        'steps': {
            'pam_demande': 'Request',
            'pam_analyse': 'CISO analysis',
            'pam_activation': 'Activation and revocation',
            'pam_revue': 'Log review',
            'pam_clos': 'Access closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'demande-ouverture-poste': {
        'slug_en': 'position-opening-request',
        'name': 'Position opening request',
        'description': 'Adding a position to the headcount plan',
        'steps': {
            'ouvp_demande': 'Manager request',
            'ouvp_avis_rh_step': 'HR review',
            'ouvp_controle_budget': 'Budget check',
            'ouvp_decision_step': 'Opening decision',
            'ouvp_ouvert': 'Position open',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-ouvp-soumettre': 'Submit to HR',
        },
    },
    'mobilite-interne-promotion': {
        'slug_en': 'internal-mobility-and-promotion',
        'name': 'Internal mobility and promotion',
        'description': 'Application for a move or a promotion proposal',
        'steps': {
            'mob_candidature': 'Application or proposal',
            'mob_avis_origine': 'Current manager review',
            'mob_avis_accueil': 'Receiving manager review',
            'mob_validation_rh': 'HR approval',
            'mob_accordee': 'Move approved',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-mob-soumettre': 'Submit to the current manager',
        },
    },
    'validation-periode-essai': {
        'slug_en': 'probation-period-decision',
        'name': 'Probation period decision',
        'description': 'Decision on the outcome of a probation period',
        'steps': {
            'ess_alerte': 'End-of-period alert',
            'ess_evaluation': 'Manager assessment',
            'ess_avis_rh_step': 'HR review',
            'ess_notification': 'Notice to the employee',
            'ess_confirme': 'Employee confirmed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-ess-renouveler': 'Extend the period',
        },
    },
    'gestion-consultants-externes': {
        'slug_en': 'external-consultant-management',
        'name': 'External consultant management',
        'description': 'Life cycle of an external contributor',
        'steps': {
            'cons_demande': 'Onboarding request',
            'cons_securite': 'Security approval',
            'cons_mission_active': 'Assignment running',
            'cons_cloture': 'Assignment closure',
            'cons_close': 'Assignment closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-cons-soumettre': 'Submit to Information Security',
        },
    },
    'demande-attestation-rh': {
        'slug_en': 'hr-certificate-request',
        'name': 'HR certificate request',
        'description': 'Request for an employment, salary or attendance certificate',
        'steps': {
            'att_demande': 'Request',
            'att_edition': 'Document issuance',
            'att_remise': 'Handed to the employee',
            'att_delivree': 'Certificate issued',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-att-transmettre': 'Refer to HR',
        },
    },
    'sanction-disciplinaire': {
        'slug_en': 'disciplinary-action',
        'name': 'Disciplinary action',
        'description': 'Formal disciplinary procedure',
        'steps': {
            'sanc_signalement': 'Report intake',
            'sanc_qualification': 'Legal assessment',
            'sanc_entretien': 'Preliminary interview',
            'sanc_decision': 'Decision',
            'sanc_notification': 'Notification',
            'sanc_notifiee': 'Sanction notified',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {},
    },
    'declaration-accident-travail': {
        'slug_en': 'workplace-accident-report',
        'name': 'Workplace accident report',
        'description': 'Reporting a workplace or commuting accident',
        'steps': {
            'atrav_declaration': 'Accident reporting',
            'atrav_constat': 'Findings and injuries',
            'atrav_formalite': 'Filing with the authority',
            'atrav_prevention': 'Analysis and prevention',
            'atrav_clos': 'Case closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-atrav-constater': 'Record the findings',
        },
    },
    'certification-reglementaire': {
        'slug_en': 'regulatory-certification',
        'name': 'Regulatory certification',
        'description': 'Tracking the certifications required to hold a role',
        'steps': {
            'cert_demande': 'Request',
            'cert_validation': 'Need approval',
            'cert_passage': 'Enrollment and exam',
            'cert_enregistrement': 'Recorded in the register',
            'cert_obtenue': 'Certification obtained',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-cert-soumettre': 'Submit for approval',
        },
    },
    'agrement-commercant': {
        'slug_en': 'merchant-accreditation',
        'name': 'Merchant accreditation',
        'description': 'Reviewing a merchant\'s application for card acquiring',
        'steps': {
            'agr_depot': 'Application filing',
            'agr_instruction': 'Application review',
            'agr_conformite': 'Compliance check',
            'agr_decision': 'Accreditation decision',
            'fin_termine': 'Accredited',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-agr-soumettre': 'Submit for review',
            't-agr-conformite-valider': 'Recommend approval',
            't-agr-decision-valider': 'Grant accreditation',
        },
    },
    'installation-tpe': {
        'slug_en': 'card-terminal-installation',
        'name': 'Card terminal installation',
        'description': 'Deploying a payment terminal at an accredited merchant',
        'steps': {
            'tpe_depot': 'Installation request',
            'tpe_preparation': 'Equipment preparation',
            'tpe_installation': 'On-site installation',
            'tpe_recette': 'Testing and go-live',
            'fin_termine': 'Terminal in production',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-tpe-preparation-valider': 'Equipment ready — schedule installation',
            't-tpe-installation-valider': 'Installation complete',
            't-tpe-recette-valider': 'Go live',
        },
    },
    'contestation-transaction-carte': {
        'slug_en': 'card-transaction-dispute',
        'name': 'Card transaction dispute',
        'description': 'Handling a cardholder\'s dispute over a transaction',
        'steps': {
            'ctc_depot': 'Dispute intake',
            'ctc_analyse': 'Dispute analysis',
            'ctc_instruction': 'Scheme investigation',
            'ctc_decision': 'Refund decision',
            'fin_termine': 'Dispute closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-ctc-soumettre': 'Submit for analysis',
            't-ctc-analyse-valider': 'Eligible — investigate with the scheme',
            't-ctc-instruction-valider': 'Response received — decide',
            't-ctc-decision-valider': 'Close the dispute',
        },
    },
    'traitement-chargeback': {
        'slug_en': 'chargeback-handling',
        'name': 'Chargeback handling',
        'description': 'Acquirer handling of a chargeback notified by the scheme',
        'steps': {
            'cbk_depot': 'Scheme notification',
            'cbk_qualification': 'Chargeback assessment',
            'cbk_preuves': 'Merchant evidence collection',
            'cbk_arbitrage': 'Representment or acceptance',
            'fin_termine': 'Chargeback closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-cbk-soumettre': 'Submit for assessment',
            't-cbk-qualification-valider': 'Collect evidence',
            't-cbk-preuves-valider': 'Evidence collected — decide',
            't-cbk-arbitrage-valider': 'Close the chargeback',
        },
    },
    'installation-gab': {
        'slug_en': 'atm-installation-or-relocation',
        'name': 'ATM installation or relocation',
        'description': 'Installing, relocating or replacing a cash machine',
        'steps': {
            'gab_depot': 'Need definition',
            'gab_etude': 'Site survey',
            'gab_investissement': 'Investment approval',
            'gab_deploiement': 'Deployment and go-live',
            'fin_termine': 'ATM in service',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-gab-soumettre': 'Submit for survey',
            't-gab-etude-valider': 'Survey favorable — submit for approval',
            't-gab-investissement-valider': 'Approve the investment',
            't-gab-deploiement-valider': 'Bring into service',
        },
    },
    'demande-badge-acces': {
        'slug_en': 'access-badge-request',
        'name': 'Access badge request',
        'description': 'Issuing, renewing or deactivating a site access badge',
        'steps': {
            'bdg_depot': 'Request',
            'bdg_hierarchie': 'Manager approval',
            'bdg_securite': 'Security approval',
            'bdg_remise': 'Production and handover',
            'fin_termine': 'Badge issued',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-bdg-hierarchie-valider': 'Refer to Information Security',
            't-bdg-securite-valider': 'Authorize badge production',
            't-bdg-remise-valider': 'Badge issued',
        },
    },
    'demande-materiel': {
        'slug_en': 'equipment-request',
        'name': 'Equipment request',
        'description': 'Issuing IT equipment, furniture or supplies',
        'steps': {
            'mat_depot': 'Need definition',
            'mat_validation': 'Budget approval',
            'mat_stock': 'Stock check',
            'mat_remise': 'Allocation and handover',
            'fin_termine': 'Equipment delivered',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-mat-validation-valider': 'Approve — check stock',
            't-mat-stock-valider': 'In stock — prepare handover',
            't-mat-remise-valider': 'Equipment delivered',
        },
    },
    'reservation-salle-reunion': {
        'slug_en': 'meeting-room-booking',
        'name': 'Meeting room booking',
        'description': 'Booking a room with its equipment and logistics',
        'steps': {
            'sal_depot': 'Booking request',
            'sal_disponibilite': 'Availability check',
            'sal_preparation': 'Room preparation',
            'fin_termine': 'Booking confirmed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-sal-disponibilite-valider': 'Room assigned — prepare',
            't-sal-preparation-valider': 'Room ready',
        },
    },
    'demande-vehicule-service': {
        'slug_en': 'company-vehicle-request',
        'name': 'Company vehicle request',
        'description': 'Making a fleet vehicle available',
        'steps': {
            'veh_depot': 'Assignment request',
            'veh_validation': 'Travel approval',
            'veh_affectation': 'Vehicle allocation',
            'veh_retour': 'Return and inspection',
            'fin_termine': 'Assignment closed',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-veh-validation-valider': 'Approve — assign a vehicle',
            't-veh-affectation-valider': 'Vehicle handed over — assignment in progress',
            't-veh-retour-valider': 'Close the assignment',
        },
    },
    'maintenance-batiment': {
        'slug_en': 'building-maintenance-request',
        'name': 'Building maintenance request',
        'description': 'Reporting and handling a fault on a site',
        'steps': {
            'mnt_depot': 'Issue reporting',
            'mnt_diagnostic': 'Diagnosis',
            'mnt_validation': 'Works approval',
            'mnt_realisation': 'Works and sign-off',
            'fin_termine': 'Works signed off',
            'fin_rejete': 'Rejected',
            'fin_annule': 'Canceled',
        },
        'transitions': {
            't-mnt-soumettre': 'Submit for diagnosis',
            't-mnt-diagnostic-valider': 'Diagnosis made — submit for approval',
            't-mnt-validation-valider': 'Approve the works',
            't-mnt-realisation-valider': 'Sign off the works',
        },
    },
}
