# -*- coding: utf-8 -*-
"""Traductions anglaises du catalogue, indexées par le rang du portefeuille."""

# index -> (nom, description courte, [3 étapes])
EN = {
 1: ("Leave request", "Leave and absence requests", ["New request", "Awaiting approval", "Approved"]),
 2: ("Expense report", "Submission and reimbursement of business expenses", ["New report", "Accounting check", "Management approval"]),
 3: ("Support ticket", "Requests, incidents and bugs", ["New ticket", "Triage", "In progress"]),
 4: ("Purchase request", "Purchase approval circuit", ["New request", "Line manager approval", "Second-level approval (high amount)"]),
 5: ("Employee onboarding", "Bringing a new employee on board", ["New arrival", "IT preparation", "HR welcome"]),
 6: ("Customer complaint", "Complaints and disputes", ["New complaint", "Analysis", "Handling"]),
 7: ("Access rights", "Access requests to applications, databases and internal tools", ["New request", "Manager approval", "Application owner approval"]),
 8: ("Application change management", "Changes and releases on business applications", ["Submission", "IT analysis", "Application owner approval"]),
 9: ("Supplier contracts", "Reviewing and securing supplier contracts before signature", ["Contract filed", "Legal review", "Financial approval"]),
 10: ("Employee training", "Training requests", ["Training request", "Manager approval", "HR budget check"]),
 11: ("Business travel", "Assignments and business trips", ["Travel request", "Manager approval", "Financial approval"]),
 12: ("Recruitment campaign", "From opening a position to the candidate joining", ["Hiring need", "HR approval", "Budget approval"]),
 13: ("Internal audits", "Planning internal audits and tracking corrective actions", ["Planning", "Fieldwork", "Report approval"]),
 14: ("Internal legal requests", "Requests addressed to the legal department", ["Request", "Triage", "Legal analysis"]),
 15: ("Annual reviews", "Annual appraisal campaigns", ["Campaign launch", "Manager interview", "Employee comment"]),
 16: ("Employee offboarding", "Securing an employee's departure", ["Launch", "Manager confirmation", "IT deactivation"]),
 17: ("Suspicious activity report", "AML reporting of an unusual transaction by an employee", ["Report raised", "Compliance analysis", "Filing decision"]),
 18: ("Client onboarding (KYC)", "Opening a business relationship", ["File collection", "Document verification", "Screening and scoring"]),
 19: ("Periodic KYC review", "Updating the client knowledge file at the interval set by the segment", ["Review planning", "Collection from the client", "Analysis and re-rating"]),
 20: ("High-risk client approval (PEP)", "Escalation of a politically exposed or high-risk client", ["Case raised", "Compliance analysis", "Executive approval"]),
 21: ("Conflict of interest disclosure", "Disclosure of a potential or actual conflict of interest", ["Disclosure", "Manager opinion", "Ethics officer review"]),
 22: ("Gift and hospitality disclosure", "Disclosure of a gift or invitation received or offered", ["Disclosure", "Threshold check", "Ethics officer decision"]),
 23: ("New product committee", "Review of a new product, service or distribution channel", ["Scoping", "Risk opinion", "Compliance and legal opinion"]),
 24: ("Regulatory review", "Taking a new regulatory text into account", ["Watch", "Impact analysis", "Compliance plan"]),
 25: ("Operational incident report", "Collecting an operational incident under the Basel taxonomy", ["Report raised", "Assessment and costing", "Analysis and action plan"]),
 26: ("Risk self-assessment (RCSA)", "Self-assessment of risks and controls by entity", ["Campaign launch", "Self-assessment by the entity", "Risk challenge"]),
 27: ("Permanent control campaign", "Running a second-line control from the plan", ["Planning", "Control performed", "Risk supervision"]),
 28: ("Audit recommendation follow-up", "Following a recommendation from internal audit or inspection", ["Recorded", "Action plan", "Implementation"]),
 29: ("Security incident report", "Handling an information security incident", ["Report raised", "Assessment", "Handling and notification"]),
 30: ("Security exception approval", "Request to deviate from a security policy rule", ["Request", "CISO analysis", "Risk acceptance"]),
 31: ("Access rights recertification", "Recertification campaign of application access rights", ["Campaign launch", "Manager review", "Removals applied"]),
 32: ("Spend commitment approval", "Prior authorisation of a budget commitment", ["Commitment request", "Budget check", "Approval by delegation"]),
 33: ("Supplier invoice approval", "Checking an incoming invoice", ["Invoice received", "Service confirmed", "Accounting check"]),
 34: ("Supplier bank details change", "Creating a third party or changing its bank details, with mandatory call-back", ["Request", "Call-back and verification", "Dual approval"]),
 35: ("Payment order approval", "Four-eyes approval circuit for a payment order", ["Order entered", "Treasury check", "Signature"]),
 36: ("Exceptional payment request", "Payment outside the normal circuit — urgency, no purchase order, off schedule", ["Request", "Finance review", "Executive arbitration"]),
 37: ("Risk limit breach request", "Authorisation to exceed a risk limit — counterparty, sector, country", ["Request", "Risk analysis", "Committee decision"]),
 38: ("Exceptional credit approval", "Credit granted outside policy — rate, term, ratio, collateral", ["File prepared", "Credit risk analysis", "Credit committee"]),
 39: ("Delegation of authority", "Granting, changing or withdrawing a delegation of authority or signature", ["Request", "Incompatibility check", "Executive approval"]),
 40: ("Complex claims handling", "Handling a high-stakes claim — large amount, several victims, suspected fraud", ["Claim reported", "Assessment", "Cover analysis"]),
 41: ("Exceptional settlement approval", "Settlement outside the contract or scale — goodwill, cap exceeded", ["Request", "Technical opinion", "Executive decision"]),
 42: ("Broker accreditation", "Accrediting an insurance intermediary", ["Application", "Licence verification", "Compliance check"]),
 43: ("Litigation management", "Opening and following a litigation file", ["File opened", "Legal assessment", "Proceedings followed"]),
 44: ("Contract renewal or termination", "Handling a contract deadline before notice expires", ["Deadline alert", "Relationship review", "Arbitration"]),
 45: ("Supplier accreditation", "Approving a new supplier", ["Accreditation request", "Due diligence", "Third-party risk assessment"]),
 46: ("Periodic supplier review", "Performance and risk review of an accredited supplier", ["Review launch", "Rating by the requester", "Risk review"]),
 47: ("Tender and sourcing", "Putting a purchasing need out to tender", ["Preparation", "Market consultation", "Bid analysis"]),
 48: ("Internal policy approval", "Life cycle of the internal documentation", ["Drafting", "Compliance and legal review", "Executive approval"]),
 49: ("New project request", "Reviewing an IT project request", ["Need expressed", "Scoping and costing", "Prioritisation"]),
 50: ("Architecture approval", "Taking an architecture file to committee", ["File submitted", "Technical review", "Security review"]),
 51: ("Major incident", "Crisis management of a critical incident", ["Declared", "Assessment and crisis team", "Service restored"]),
 52: ("Problem management", "Finding the root cause of recurring incidents", ["File opened", "Root cause analysis", "Permanent fix"]),
 53: ("Privileged account management", "Granting privileged or emergency access", ["Request", "CISO analysis", "Activation and revocation"]),
 54: ("Position opening request", "Adding a position to the headcount plan", ["Manager request", "HR opinion", "Budget check"]),
 55: ("Internal mobility and promotion", "Application for a move or a promotion proposal", ["Application or proposal", "Current manager opinion", "Receiving manager opinion"]),
 56: ("Probation period decision", "Decision on the outcome of a probation period", ["End-of-period alert", "Manager assessment", "HR opinion"]),
 57: ("External consultant management", "Life cycle of an external contributor", ["Onboarding request", "Security approval", "Assignment running"]),
 58: ("HR certificate request", "Request for an employment, salary or attendance certificate", ["Request", "Document issued", "Handed to the employee"]),
 59: ("Disciplinary action", "Formal disciplinary procedure", ["Report raised", "Legal assessment", "Preliminary interview"]),
 60: ("Workplace accident report", "Reporting a workplace or commuting accident", ["Report raised", "Findings and injuries", "Filed with the authority"]),
 61: ("Regulatory certification", "Tracking the certifications required to hold a role", ["Request", "Need approved", "Enrolment and exam"]),
 62: ("Merchant accreditation", "Reviewing a merchant's application for card acquiring", ["Application filed", "Application review", "Compliance check"]),
 63: ("Card terminal installation", "Deploying a payment terminal at an accredited merchant", ["Installation request", "Equipment prepared", "On-site installation"]),
 64: ("Card transaction dispute", "Handling a cardholder's dispute over a transaction", ["Dispute received", "Dispute analysis", "Filed with the scheme"]),
 65: ("Chargeback handling", "Acquirer handling of a chargeback notified by the scheme", ["Scheme notification", "Chargeback assessment", "Merchant evidence collected"]),
 66: ("ATM installation or relocation", "Installing, relocating or replacing a cash machine", ["Need expressed", "Site survey", "Investment approval"]),
 67: ("Access badge request", "Issuing, renewing or deactivating a site access badge", ["Request", "Manager approval", "Security approval"]),
 68: ("Equipment request", "Issuing IT equipment, furniture or supplies", ["Need expressed", "Budget approval", "Stock check"]),
 69: ("Meeting room booking", "Booking a room with its equipment and logistics", ["Booking request", "Availability check", "Room prepared"]),
 70: ("Company vehicle request", "Making a fleet vehicle available", ["Assignment request", "Travel approval", "Vehicle allocated"]),
 71: ("Building maintenance request", "Reporting and handling a fault on a site", ["Reported", "Diagnosis", "Works approved"]),
}
